-- begin HIERARCHY_ITEM
alter table HIERARCHY_ITEM add constraint FK_HIERARCHY_ITEM_ON_TEAM foreign key (TEAM_ID) references HIERARCHY_TEAM(ID)^
alter table HIERARCHY_ITEM add constraint FK_HIERARCHY_ITEM_ON_PARENT foreign key (PARENT_ID) references HIERARCHY_ITEM(ID) on delete CASCADE^
create index IDX_HIERARCHY_ITEM_ON_TEAM on HIERARCHY_ITEM (TEAM_ID)^
create index IDX_HIERARCHY_ITEM_ON_PARENT on HIERARCHY_ITEM (PARENT_ID)^
-- end HIERARCHY_ITEM
-- begin HIERARCHY_CAPACITY
alter table HIERARCHY_CAPACITY add constraint FK_HIERARCHY_CAPACITY_ON_TEAM foreign key (TEAM_ID) references HIERARCHY_TEAM(ID)^
create index IDX_HIERARCHY_CAPACITY_ON_TEAM on HIERARCHY_CAPACITY (TEAM_ID)^
-- end HIERARCHY_CAPACITY
